fruits=["apple", "banana", "cherry", "date", ]
print("Original list", list)
print("First fruit", fruits[0])
print("Last fruit",fruits[-1])
fruits.append("elderberry")
print("After appending",fruits)
fruits.insert(1,"blueberry")
print("After inserting at index 1",fruits)
fruits.remove("cherry")
print("After removing 'cgerry'",fruits)
popped_fruit=fruits.pop()
print("Popped fruit",popped_fruit)
print("After popping",fruits)
fruits.sort()
print("Second list",fruits)
fruits.reverse()
print("Reverse list",fruits)
print("Iterating over the list")
for fruit in fruits:
    print(fruit)